<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tratamento de Erro - Try Catch Finally</title>
</head>
<body>
    <script>

        var num; // Máx=10
        try {
            num=prompt("Digite um valor");
            if(num>10){
                throw new Error("Valor inválido, o valor máximo é 10<br>");    // gerando um erro manualmente.
            }
            document.write("Valor: "+num);            
        } catch (error) {
            document.write("Valor: " + error.message);                 // mostra o erro explícito para o usuário
            //console.log("Mensagem de erro: "+ error.message);         //mostra o erro no console. Não explícito para o usuário
        }finally{
            document.write("Fim do tratamento");
        }



        /* 
            try -> rotina passível de geração de erro;
            catch -> tratamento do erro;
            finally -> opcional. é executado ocorrendo ou não um erro.
                throw new err
        */
    </script>
    
</body>
</html>